[package]
name = "universal_rust_server_software"
version = "0.1.0"
authors = ["URSS"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.76"
publish = false

[dependencies]
bevy = "0.13.2"